# $FreeBSD$

MAINTAINER=tyler@freebsd.org

LIB=launch
SRCS=liblaunch.c libbootstrap.c \
	launch_getters.c \
	launch_data.c # XXX: Disabled, see #5 libvproc.c

.include <../launchd.mk>
.include <bsd.lib.mk>

