#!/bin/sh

##
# Apple File Protocol
##

[ -f /System/Library/LaunchDaemons/com.apple.AppleFileServer.plist ] && exit 0

. /etc/rc.common

StartService ()
{
    if [ "${AFPSERVER:=-NO-}" = "-YES-" ]; then
	echo "Starting Apple File Service"
	/usr/sbin/AppleFileServer
    fi
}

StopService ()
{
    return 0
}

RestartService ()
{
    return 0
}

RunService "$1"
