#!/bin/sh

##
# Local filesystems
##

. /etc/rc.common

StartService ()
{
    echo "Checking disks"
    /sbin/autodiskmount -va
}

StopService ()
{
    return 0;
}

RestartService ()
{
    return 0;
}

RunService "$1"
