#!/bin/sh

##
# IP Services
##

[ -f /System/Library/LaunchDaemons/com.apache.httpd.plist ] && exit 0

. /etc/rc.common

StartService ()
{
	if [ -a /etc/com.apple.named.conf.proxy ]
	then
		echo "Starting Internet address sharing"
		/usr/libexec/InternetSharing
	fi
}

StopService ()
{
    return 0
}

RestartService ()
{
    return 0
}

RunService "$1"
