#!/bin/sh

##
# This startup item's main purpose is to signal
# SystemStarter that we are now ready to start LoginWindow.
##

. /etc/rc.common


StartService ()
{
    # leave cookie for Login Window
    /usr/bin/touch /var/run/.systemStarterRunning
}

StopService ()
{
    return 0;
}

RestartService () { StartService; }


RunService "$1"
