#!/bin/sh

. /etc/rc.common

StartService ()
{

    if [ -f /usr/sbin/mDNSResponder ]; then
        if pid=$(GetPID mDNSResponder); then
            return 0
        else
            echo "Starting Multicast DNS Responder"
            /usr/sbin/mDNSResponder
        fi
    fi
}

StopService ()
{
    if pid=$(GetPID mDNSResponder); then
	echo "Stopping Multicast DNS Responder"
	kill -TERM "${pid}"
    else
	echo "Multicast DNS Responder is not running."
    fi
}

RestartService () { StopService; StartService; }

RunService "$1"
