#!/bin/sh

##
# Configure network interfaces and host name
##

. /etc/rc.common

StartService ()
{
	ConsoleMessage "Initializing network"

	ipconfig waitall > /dev/null 2>&1

	if [ "${IPV6:=-YES-}" = "-NO-" ]
	then
		sysctl -w net.inet6.ip6.auto_on=0 > /dev/null
		ip6 -x
	fi

	if [ "${IPFORWARDING:=-NO-}" = "-YES-" ]
	then
		sysctl -w net.inet.ip.forwarding=1 > /dev/null
	else
		sysctl -w net.inet.ip.forwarding=0 > /dev/null
	fi

}

StopService ()
{
	return 0
}

RestartService ()
{
	return 0
}

RunService "$1"
