#!/bin/sh

##
# Load network kernel modules
##

. /etc/rc.common

StartService ()
{
	fwHelper=/System/Library/PrivateFrameworks/NetworkConfig.framework/Resources/firewalltool
	fwConfig=/Library/Preferences/com.apple.sharing.firewall.plist

	if [ -x "${fwHelper}" -a -f "${fwConfig}" ]; then
		${fwHelper}
	fi

	if [ "${VPNSERVER:=-NO-}" = "-YES-" ]; then
		vpnd
	fi
}

StopService ()
{
    return 0
}

RestartService ()
{
    return 0
}

RunService "$1"
