.Dd September 28, 2005
.Dt BPORTS 1
.Os "Mac OS X" 10.5
.Sh NAME
.Nm bports
.Nd Show Mach bootstrap services and servers
.Sh SYNOPSIS
.Nm
.Op PID
.Sh DESCRIPTION
The
.Nm
program prints out Mach bootstrap servers, their services and their respective states. While the namespace appears flat, it is in fact hierarchical, thus allowing for certain services to be only available to a subset or processes or users. The three states a service can be in are active ("A"), in-active ("I") and on-demand ("D").
