.Dd February 2, 2005
.Dt launchd_helperd 8 
.Os Darwin
.Sh NAME
.Nm launchd_helperd
.Nd Monitors the system and tells launchd to start jobs
.Sh SYNOPSIS
.Nm
.Op Fl T Ar tclcode
.Sh DESCRIPTION
.Nm 
monitors the system and tells
.Nm launchd
to start or stop jobs given specific combinations of events that transpire on the system.
For more information, see
.Xr launch_Tcl 5 .
.Sh OPTIONS
.Bl -tag -width -indent
.It Fl T
Test Tcl code for use with
.Nm launchd .
The argument must either Tcl code itself, or a path to a file.
.El
.Sh NOTES
DO NOT block or sleep in your Tcl code. That will stall the whole daemon.
.Sh SEE ALSO 
.Xr launchctl 1 ,
.Xr launch_Tcl 5 ,
.Xr launchd.plist 5 ,
.Xr launchd 8
