.Dd February 2, 2005
.Dt launch_Tcl 5
.Os Darwin
.Sh NAME
.Nm launch_Tcl
.Nd Tcl commands available in launchd
.Sh DESCRIPTION
.Nm
documents all of the Tcl commands available for use in a
.Xr launchd.plist 5 .
.Sh COMMANDS
.Bl -tag -width -indent
.It Ar StartJob
Start the job that contains the given Tcl code in the plist.
.It Ar StopJob
Stop the job that contains the given Tcl code in the plist.
.It Ar CallBackInterval Ar seconds Op Ar eventname
Re-evaluate the script every N seconds.
.It Ar CallBackDate Ar clock Op Ar eventname
Re-evaluate the script at the given clock date.
.It Xo Ar WatchPath Op Fl dwealrRC
.Ar path Op Ar eventname
.Xc
Re-evaluate the script if the given path changes.
.Bl -tag -width -indent
.It Fl d
Watch to see if the path is deleted.
.It Fl w
Watch to see if the path is written to.
.It Fl e
Watch to see if the path is extended.
.It Fl a
Watch to see if the path attributes change.
.It Fl l
Watch to see if the path link count changes.
.It Fl r
Watch to see if the path is renamed.
.It Fl R
Watch to see if the path is revoked.
.It Fl C
Cancel the given watch path.
.El
.It Ar CancelAllCallBacks
Cancel all possible outstanding reasons the script might be re-evaluated.
.It Ar syslog Ar level Ar message
Log the given message at level to the system log. The available levels include:
emergency, alert, critical, error, warning, notice, info and debug.
.It Ar GetProperty
Get a given property from the system. Currently the only option is: onbattery.
.El
.Sh FILES
.Bl -tag -width "/System/Library/LaunchDaemons" -compact
.It Pa ~/Library/LaunchAgents
Per-user agents provided by the user.
.It Pa /Library/LaunchAgents
Per-user agents provided by the administrator.
.It Pa /Library/LaunchDaemons
System wide daemons provided by the administrator.
.It Pa /System/Library/LaunchAgents
Mac OS X Per-user agents.
.It Pa /System/Library/LaunchDaemons
Mac OS X System wide daemons.
.El
.Sh SEE ALSO 
.Xr launchd.plist 5 ,
.Xr launchd.conf 5 ,
.Xr launchd_helperd 8 ,
.Xr launchd 8
