.Dd September 30, 2004
.Dt launchctl 1
.Os Darwin
.Sh NAME
.Nm launchctl
.Nd Interfaces with launchd
.Sh SYNOPSIS
.Nm
.Op Fl w
.Op Fl l Ar xmlfile
.Op Fl u Ar xmlfile
.Sh DESCRIPTION
.Nm 
interfaces with
.Nm launchd
to load and unload daemons and agents.
.Sh OPTIONS
.Bl -tag -width -indent
.It Fl w
Write to the XML property list. This updates the disabled boolean at the same time as a load or unload command given to this tool.
.It Fl l Ar xmlfile
Load the daemon/agent described in the XML property list into
.Nm launchd .
This ignores daemons/agents marked as disabled in the XML property list.
.It Fl u Ar xmlfile
Unload the daemon/agent described in the XML property list from
.Nm launchd .
.El
.Sh FILES
.Bl -tag -width "/System/Library/LaunchDaemons" -compact
.It Pa ~/Library/LaunchAgents
Per-user agents provided by the user.
.It Pa /Library/LaunchAgents
Per-user agents provided by the administrator.
.It Pa /Library/LaunchDaemons
System wide daemons provided by the administrator.
.It Pa /System/Library/LaunchAgents
Mac OS X Per-user agents.
.It Pa /System/Library/LaunchDaemons
Mac OS X System wide daemons.
.El
.Sh SEE ALSO 
.Xr launchd 8 ,
.Xr launch.plist 5
