#!/bin/sh

unset LAUNCHD_SOCKET

set -e

# don't let people kill us. We shouldn't be long, so this isn't a big deal.

trap "" TSTP
trap "" HUP
trap "" INT
trap "" QUIT
trap "" TERM

if [ $# -eq 0 ]
then
   echo "Usage: $(basename $0) --list | <service-name> <command>" >&2
   exit 1
fi

if [ "$1" == "--list" ]
then
	cd /System/Library/LaunchDaemons 2>/dev/null
	ls -1 | egrep '.plist$' | sed 's,.plist$,,g'
	exit 0
elif [ "$1" == "--test-if-configured-on" ]
then
	if [ -f /System/Library/LaunchDaemons/$2.plist ]
	then
		IS_OFF=$(defaults read /System/Library/LaunchDaemons/$2 Disabled 2>/dev/null || true)
		if [ "$IS_OFF" = 1 ]
		then
			exit 1
		else
			exit 0
		fi
	fi
	exit 1
elif [ "$1" == "--test-if-available" ]
then
	[ -f /System/Library/LaunchDaemons/$2.plist ] && exit 0
	exit 1
elif [ -f "/System/Library/LaunchDaemons/$1.plist" ]
then
	[ "$2" == start ] && launchctl load -w /System/Library/LaunchDaemons/$1.plist
	[ "$2" == stop  ] && launchctl unload -w /System/Library/LaunchDaemons/$1.plist
else
	echo "No such service $1" >&2
	exit 1
fi
