.Dd December 14, 2006
.Dt shutdown_debugger 8 
.Os Darwin
.Sh NAME
.Nm shutdown_debugger
.Nd tool to aid debugging shutdowns
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
This tool is invoked a few seconds after a shutdown or reboot request to figure out why the machine isn't off yet. Useful debug files are placed in /var/log/shutdown.
